### ISSUE TITLE
Zmiany w widok "Lista uczniów w klasie

### ISSUE THREAD

**Issue by lubinetpl** [lokalni/kl-backend#18]
Dodać w naglowku:
- nazwę klasy 
- przycisk "Rozpocznij lekcje"

**Comment by mmankows** [comment]
@lubinetpl zobacz prosze, wrzucilem nowa wersje i zamknij jak ok

![obraz](https://user-images.githubusercontent.com/4417421/78686960-eb66f280-78f3-11ea-86f6-42b60fe9a1f9.png)

**Comment by lubinetpl** [comment]
Dzięki
