### ISSUE TITLE
Agree server <-> backend handshake

### ISSUE THREAD

**Issue by consi** [lokalni/kl-backend#3]
First handshake proposition described below

Each BBB server will have subdomain in our domain name which for now is called agooddomain.pl

1. BBB server sends a handshake message on boot to landing page backend uri /api/v1/register with json body:
```
{ "bbb_hostname": "http://bbb1.agooddomain.pl/", "api_secret": "here_goes_bbb_api_secret" }
```

2. Next backend compares `bbb1.agooddomain.pl` if it contains `agooddomain.pl`, if yes, then backend tries to establish communication to BBB api on `https://bbb1.agooddomain.pl/bigbluebutton/api/getMeetings` with secret provided by BBB server on 1st point.

3. If previous request was sucessful then pair of host+secret is saved to database

Keepalive protocol:
1. Each bbb server sends keepalive json message to `/api/v1/keepalive`:
```
{
	"cpu_count": 4,
	"load_5m": 0.34,
	"api_secret": "here_goes_bbb_api_secret",
	"hostname": "bbb1.agooddomain.pl",
	"region_name": "slask"
}
```

*cpu_count* - means total core count on machine
*load_5m* - server 5min load average
*api_secret* - BBB api secret (used to authorize this keepalive together with hostname)
*hostname* - BBB  hostname (same purpose as above + to identify this machine)
*region_name* - slask (Voivodeship name lowercase without polish characters to split loadbalancing to voivodeship level)

**Comment by consi** [comment]
@mmankows any thoughts?

**Comment by mmankows** [comment]
Looks fine 👍
